version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/brentnd/git-get
    steps:
      - checkout
      - run:
          name: Deps
          command: go get -v -t -d ./...
      - run:
          name: Build
          command: go build -o build/git-get main.go
      - run:
          name: Unit Tests
          command: go test -v -cover -race
      - run:
          name: Install
          command: cp build/git-get $GOPATH/bin
      - run:
          name: Integration Test
          command: |
            git get &> test.out || true
            grep 'usage' test.out
            git get github.com/brentnd/git-get &> test.out
            grep 'already exists' test.out
            GOPATH=/tmp git get github.com/brentnd/git-get
            ls /tmp/src/github.com/brentnd/git-get/README.md